# git add .streamlit/config.toml
# git commit -m "Add Streamlit config with Google Auth for abeattie112@gmail.com"
# git push


[server]
headless = true

[client]
showErrorDetails = true

[theme]
primaryColor = "#6eb52f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[auth]
enable = true
email_whitelist = ["abeattie112@gmail.com", "madimesenbrink19@gmail.com"]

